/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */
/* Production: uses environment variables when available */

// В production используем переменные окружения, в разработке - hardcoded значения
export const projectId = 
  (typeof import.meta !== 'undefined' && import.meta.env?.VITE_SUPABASE_PROJECT_ID) || 
  "hpcwkbkglggimwcbxpoh";

export const publicAnonKey = 
  (typeof import.meta !== 'undefined' && import.meta.env?.VITE_SUPABASE_ANON_KEY) || 
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhwY3drYmtnbGdnaW13Y2J4cG9oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgzNjEyODEsImV4cCI6MjA4MzkzNzI4MX0.CPw2nd06xBdqp0gr36wabDoXGG-64lGN7d-mYEImX8g";